package com.trekmate.app.core.ble

/**
 * BLE advertisement payload layout for TrekMate MVP.
 *
 * Manufacturer-specific data format (placed in AdvertiseData.addManufacturerData):
 *   [0..1]   : MANUFACTURER_ID (2 bytes, little-endian) — handled by Android API
 *   [0..15]  : userId bytes (16 bytes, UTF-8 — full 16-char hex userId)
 *   [16..23] : groupId bytes (8 bytes, UTF-8 — 8-char ALPHANUM groupId from server)
 *
 * Total payload: 24 bytes.
 * Android BLE manufacturer data limit: ~26 bytes (31-byte packet - 5-byte overhead).
 * ✅ 24 bytes is safely within the limit.
 *
 * IMPORTANT: userId must be exactly 16 chars (generated by UserIdGenerator).
 * groupId must be exactly 8 chars (generated by server backend).
 */
object BlePacketConstants {
    const val MANUFACTURER_ID: Int = 0x4D54  // 'TM' — TrekMate
    const val USER_ID_BYTES: Int = 16         // Full 16-char hex userId
    const val GROUP_ID_BYTES: Int = 8         // 8-char ALPHANUM groupId from server
    const val TOTAL_PAYLOAD_BYTES: Int = USER_ID_BYTES + GROUP_ID_BYTES  // 24
}

